
services:
  db:
    image: postgres:latest
    container_name: stentor-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_stentor:/var/lib/postgresql/data/
    networks:
      - stentor-network

volumes:
  postgres_stentor:

networks:
  stentor-network:
    driver: bridge