# Generated by Django 6.0.1 on 2026-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rundown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('air_time', models.TimeField(null=True)),
                ('air_day', models.DateField(null=True)),
                ('air_year', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RundownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
