# Generated by Django 6.0.1 on 2026-01-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rundown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('air_hour', models.IntegerField(default=0)),
                ('air_day', models.IntegerField(default=0)),
                ('air_month', models.IntegerField(default=0)),
                ('air_year', models.IntegerField(default=0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rundown_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rundown_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-air_year', '-air_month', '-air_day', '-air_hour'],
            },
        ),
        migrations.CreateModel(
            name='RundownNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_time', models.TimeField()),
                ('position', models.PositiveIntegerField(default=1000)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_news', to='news.news')),
                ('rundown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown', to='rundowns.rundown')),
            ],
        ),
        migrations.AddField(
            model_name='rundown',
            name='news',
            field=models.ManyToManyField(through='rundowns.RundownNews', to='news.news'),
        ),
        migrations.AddConstraint(
            model_name='rundownnews',
            constraint=models.UniqueConstraint(fields=('rundown', 'news'), name='uniq_rundown_news'),
        ),
    ]
