# Generated by Django 6.0.1 on 2026-01-27 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_initial'),
        ('rundowns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rundown',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rundown_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rundown',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rundown_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rundownnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_news', to='news.news'),
        ),
        migrations.AddField(
            model_name='rundownnews',
            name='rundown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown', to='rundowns.rundown'),
        ),
        migrations.AddField(
            model_name='rundown',
            name='news',
            field=models.ManyToManyField(through='rundowns.RundownNews', to='news.news'),
        ),
        migrations.AddConstraint(
            model_name='rundownnews',
            constraint=models.UniqueConstraint(fields=('rundown', 'news'), name='uniq_rundown_news'),
        ),
    ]
