# Generated by Django 6.0.1 on 2026-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RundownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='rundown',
            name='duration',
        ),
    ]
