# Generated by Django 6.0.1 on 2026-01-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category'),
        ('rundowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundowns_items', to='news.news'),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='rundown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundowns_items', to='rundowns.rundown'),
        ),
    ]
