# Generated by Django 6.0.1 on 2026-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='air_time',
            field=models.TimeField(default=None),
        ),
    ]
