# Generated by Django 6.0.1 on 2026-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rundown',
            name='air_day',
        ),
        migrations.RemoveField(
            model_name='rundown',
            name='air_time',
        ),
        migrations.RemoveField(
            model_name='rundown',
            name='air_year',
        ),
        migrations.RemoveField(
            model_name='rundown',
            name='title',
        ),
        migrations.AddField(
            model_name='rundown',
            name='air_date',
            field=models.DateTimeField(null=True),
        ),
    ]
