# Generated by Django 6.0.1 on 2026-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundown',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
