# Generated by Django 6.0.1 on 2026-01-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0002_alter_rundownnews_news_alter_rundownnews_rundown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('rundowns_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocks', to='rundowns.rundownnews')),
            ],
        ),
    ]
