# Generated by Django 6.0.1 on 2026-01-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_creator'),
        ('rundowns', '0002_alter_rundown_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='news.news'),
        ),
    ]
