# Generated by Django 6.0.1 on 2026-01-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0002_alter_rundownnews_air_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='air_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
