# Generated by Django 6.0.1 on 2026-01-27 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 17, 42, 29, 965751, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 17, 42, 29, 944140, tzinfo=datetime.timezone.utc)),
        ),
    ]
