# Generated by Django 6.0.1 on 2026-02-08 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_locked_by'),
        ('rundowns', '0003_alter_rundown_created_by_alter_rundown_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rundown',
            constraint=models.UniqueConstraint(fields=('air_hour', 'air_day', 'air_month', 'air_year'), name='unique_airt_time'),
        ),
    ]
