# Generated by Django 6.0.1 on 2026-01-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('rundowns', '0003_alter_rundownnews_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundown',
            name='assets',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset'),
        ),
    ]
