# Generated by Django 6.0.1 on 2026-01-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0003_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocks',
            options={'verbose_name_plural': 'Blocks'},
        ),
    ]
