# Generated by Django 6.0.1 on 2026-01-26 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0003_alter_rundownnews_air_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='air_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 26, 13, 47, 2, 116092, tzinfo=datetime.timezone.utc)),
        ),
    ]
