# Generated by Django 6.0.1 on 2026-01-27 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0004_alter_rundownnews_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 17, 47, 12, 611291, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 17, 47, 12, 588716, tzinfo=datetime.timezone.utc)),
        ),
    ]
