# Generated by Django 6.0.1 on 2026-01-26 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0004_alter_rundownnews_air_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='air_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 26, 15, 10, 45, 860921, tzinfo=datetime.timezone.utc)),
        ),
    ]
