# Generated by Django 6.0.1 on 2026-01-27 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0005_alter_rundownnews_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 18, 13, 34, 540880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 18, 13, 34, 517280, tzinfo=datetime.timezone.utc)),
        ),
    ]
