# Generated by Django 6.0.1 on 2026-01-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('rundowns', '0005_remove_rundown_assets_rundownnews_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rundownnews',
            options={},
        ),
        migrations.RemoveField(
            model_name='rundownnews',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='rundownnews',
            name='block',
        ),
        migrations.RemoveField(
            model_name='rundownnews',
            name='position',
        ),
        migrations.CreateModel(
            name='RundownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1000)),
                ('assets', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rundowns.category')),
                ('rundown_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rundowns.rundownnews')),
            ],
        ),
    ]
