# Generated by Django 6.0.1 on 2026-01-26 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0005_alter_rundownnews_air_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rundownnews',
            name='air_time',
        ),
        migrations.AddField(
            model_name='rundownnews',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 26, 15, 19, 46, 544188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='rundownnews',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 26, 15, 19, 46, 519002, tzinfo=datetime.timezone.utc)),
        ),
    ]
