# Generated by Django 6.0.1 on 2026-01-26 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0006_remove_rundownnews_air_time_rundownnews_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rundownnews',
            options={'ordering': ['-position']},
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 26, 15, 54, 2, 657599, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 26, 15, 54, 2, 630480, tzinfo=datetime.timezone.utc)),
        ),
    ]
