# Generated by Django 6.0.1 on 2026-01-27 19:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0006_alter_rundownnews_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 19, 59, 40, 891069, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='rundown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_news', to='rundowns.rundown'),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 1, 27, 19, 59, 40, 869198, tzinfo=datetime.timezone.utc)),
        ),
    ]
