# Generated by Django 6.0.1 on 2026-01-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('rundowns', '0006_alter_rundownnews_options_remove_rundownnews_assets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rundownitem',
            name='assets',
        ),
        migrations.AddField(
            model_name='rundownitem',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rundown_item', to='assets.asset'),
        ),
    ]
