# Generated by Django 6.0.1 on 2026-01-23 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_creator'),
        ('rundowns', '0007_remove_rundownitem_assets_rundownitem_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundown',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rundown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rundownitem',
            name='rundown_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_item', to='rundowns.rundownnews'),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_news', to='news.news'),
        ),
        migrations.AlterField(
            model_name='rundownnews',
            name='rundown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown_news', to='rundowns.rundown'),
        ),
    ]
