# Generated by Django 6.0.1 on 2026-01-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0007_alter_rundownnews_end_time_alter_rundownnews_rundown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rundownnews',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='rundownnews',
            name='start_time',
        ),
    ]
