# Generated by Django 6.0.1 on 2026-01-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0008_alter_rundown_creator_alter_rundownitem_rundown_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundownnews',
            name='rundown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rundown', to='rundowns.rundown'),
        ),
    ]
