# Generated by Django 6.0.1 on 2026-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0009_alter_rundownnews_rundown'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundownnews',
            name='position',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='RundownItem',
        ),
    ]
