# Generated by Django 6.0.1 on 2026-01-30 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0010_historicalrundownnews'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rundownnews',
            name='uniq_rundown_news',
        ),
        migrations.AlterField(
            model_name='historicalrundown',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='rundown',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
