# Generated by Django 6.0.1 on 2026-02-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rundowns', '0011_remove_rundownnews_uniq_rundown_news_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
