# Generated by Django 6.0.1 on 2026-01-11 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetref',
            name='created_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statuses.status'),
        ),
        migrations.AddField(
            model_name='assetref',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.news'),
        ),
    ]
