# Generated by Django 6.0.1 on 2026-01-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('mont', 'Монтаж'), ('edit', 'Правка'), ('final', 'Выпуск')], default='mont'),
        ),
    ]
