# Generated by Django 6.0.1 on 2026-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
