# Generated by Django 6.0.1 on 2026-01-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('news', '0003_news_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='assets.asset'),
        ),
    ]
