# Generated by Django 6.0.1 on 2026-01-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_air',
        ),
    ]
