# Generated by Django 6.0.1 on 2026-01-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_duration'),
        ('news', '0004_alter_news_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='assets.asset'),
        ),
    ]
