# Generated by Django 6.0.1 on 2026-02-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_historicalnews_is_lock_historicalnews_locked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnews',
            old_name='is_lock',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='is_lock',
            new_name='is_locked',
        ),
    ]
