# Generated by Django 6.0.1 on 2026-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_is_lock_historicalnews_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnews',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='historicalnews',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
