# Generated by Django 6.0.1 on 2026-02-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_updated_by_historicalnews_modified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnews',
            old_name='modified_by',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='modified_by',
            new_name='updated_by',
        ),
    ]
