# Generated by Django 6.0.1 on 2026-01-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
