# Generated by Django 6.0.1 on 2026-01-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_position_alter_user_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция'},
        ),
    ]
