# Generated by Django 6.0.1 on 2026-01-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_position_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиция'},
        ),
    ]
