# Generated by Django 6.0.1 on 2026-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
