# Generated by Django 6.0.1 on 2026-02-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Статус')),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
