# Generated by Django 6.0.1 on 2026-01-26 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
