# Generated by Django 6.0.1 on 2026-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='duration',
            field=models.DurationField(blank=True),
        ),
    ]
