# Generated by Django 6.0.1 on 2026-02-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_mont'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
