# Generated by Django 6.0.1 on 2026-02-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='file',
            new_name='video',
        ),
    ]
