# Generated by Django 6.0.1 on 2026-02-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_rename_file_asset_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='mont',
        ),
    ]
